name: Test

on:
  workflow_dispatch:

jobs: 
  scan:
    runs-on: ubuntu-latest
    outputs:
      report_id: ${{ steps.upload.outputs.report_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: upload
        name: NowSecure upload app
        uses: amgoodfellow/nowsecure-action/upload-app@main
        with:
          api_url: ${{ vars.API_URL }}
          lab_api_url: ${{ vars.LAB_API_URL }}
          group_id: ${{ vars.GROUP_ID }}
          platform_token: ${{ secrets.PLATFORM_TOKEN }}
          app_file: "./demo.apk"
  process:
    if: ${{ needs.scan.outputs.report_id }}
    runs-on: ubuntu-latest
    # The above stage we introduced.
    needs: scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NowSecure download report
        uses: amgoodfellow/nowsecure-action/convert-sarif@main
        timeout-minutes: 60
        with:
          report_id: ${{ needs.scan.outputs.report_id }}
          api_url: ${{ vars.API_URL }}
          lab_api_url: ${{ vars.LAB_API_URL }}
          group_id: ${{ vars.GROUP_ID }}
          platform_token: ${{ secrets.PLATFORM_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: NowSecure.sarif
